global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Spring Boot Application
  - job_name: 'cashback-api'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 4s
    static_configs:
      - targets: ['app:8080']

  # MySQL Database (if using mysqld_exporter)
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql:3306']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Jenkins
  - job_name: 'jenkins'
    static_configs:
      - targets: ['jenkins:8080']
    metrics_path: '/prometheus'
    scrape_interval: 30s

  # SonarQube
  - job_name: 'sonarqube'
    static_configs:
      - targets: ['sonarqube:9000']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093